'use client';

import { FormEvent, useEffect, useState } from 'react';
import { UserPlus } from 'lucide-react';
import { AuthDivider, AuthField, AuthLinks, AuthMessage, AuthShell, OAuthButtons } from '@/components/auth/AuthShell';
import { errorMessage } from '@/lib/auth';
import { useAuth } from '@/components/auth/AuthContext';

export default function SignupPage() {
  const { register } = useAuth(); const [form, setForm] = useState({ firstName: '', lastName: '', username: '', email: '', password: '', confirmation: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [submitting, setSubmitting] = useState(false); const [next, setNext] = useState('/dashboard/');
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('next'); if (value?.startsWith('/')) setNext(value); }, []);
  function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setMessage(''); if (form.password.length < 8) { setError('Use at least 8 characters for your password.'); return; } if (form.password !== form.confirmation) { setError('Passwords do not match.'); return; } setSubmitting(true); try { await register({ username: form.username, firstName: form.firstName, lastName: form.lastName, email: form.email, password: form.password }); setMessage('Account created. Preparing your workspace…'); window.location.replace(next); } catch (submissionError) { setError(errorMessage(submissionError, 'Unable to create your account.')); } finally { setSubmitting(false); } }
  return <AuthShell eyebrow="CREATE WORKSPACE ACCESS" title="Start building with DataSculpt." description="Create an account for your data engineering workspace. Your password is hashed in the browser before it is sent to the API."><OAuthButtons /><AuthDivider />{error && <AuthMessage error>{error}</AuthMessage>}{message && <AuthMessage>{message}</AuthMessage>}<form onSubmit={submit} className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><AuthField label="First name" name="first_name" value={form.firstName} onChange={(value) => update('firstName', value)} autoComplete="given-name" required={false} /><AuthField label="Last name" name="last_name" value={form.lastName} onChange={(value) => update('lastName', value)} autoComplete="family-name" required={false} /></div><AuthField label="Username" name="username" value={form.username} onChange={(value) => update('username', value)} placeholder="your-team-handle" autoComplete="username" /><AuthField label="Work email" name="email" type="email" value={form.email} onChange={(value) => update('email', value)} placeholder="you@company.com" autoComplete="email" /><div className="grid gap-5 sm:grid-cols-2"><AuthField label="Password" name="password" type="password" value={form.password} onChange={(value) => update('password', value)} autoComplete="new-password" /><AuthField label="Confirm password" name="confirmation" type="password" value={form.confirmation} onChange={(value) => update('confirmation', value)} autoComplete="new-password" /></div><button type="submit" disabled={submitting} className="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-brand-300/70 bg-brand-500 px-4 py-3 text-sm font-semibold text-slate-950 shadow-brand transition hover:bg-brand-300 disabled:cursor-wait disabled:opacity-70">{submitting ? 'Creating account…' : 'Create account'}<UserPlus size={16} /></button></form><AuthLinks signup /></AuthShell>;
}
