'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRight, Check, ChevronRight, Cloud, Cpu, Database, Globe2, Layers3, LockKeyhole, Network, Server, ShieldCheck, Sparkles, Target, Workflow, Zap } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/Button';
import { GlassCard } from '@/components/ui/GlassCard';
import { StatusBadge } from '@/components/ui/StatusBadge';

type Principle = { title: string; label: string; description: string; icon: typeof Cpu };
type Milestone = { year: string; title: string; description: string; icon: typeof Cpu };
type Region = { name: string; location: string; position: string; status: string };

const principles: Principle[] = [
  { title: 'Velocity First', label: 'GPU ACCELERATION', description: 'We leverage modern GPU tensor cores to eliminate compute bottlenecks and cut pipeline runtime by 90%.', icon: Zap },
  { title: 'Zero Data Drift', label: 'CONTINUOUS QUALITY', description: 'Bad data destroys AI model outputs. We enforce real-time schema validation across every pipeline run.', icon: ShieldCheck },
  { title: 'Open Interoperability', label: 'ZERO VENDOR LOCK-IN', description: 'Native integration with Apache Arrow, Iceberg, Delta Lake, Snowflake, and major vector feature stores.', icon: Network },
  { title: 'Security & Sovereignty', label: 'ENTERPRISE CONTROL', description: 'Built for single-tenant VPCs, isolated clusters, and regional compliance standards across EU, US, and APAC.', icon: LockKeyhole },
];

const milestones: Milestone[] = [
  { year: '01', title: 'Core GPU Engine R&D', description: 'Achieving 100× speedups with cuDF and CUDA primitives became the first proof point for a data layer designed around modern hardware.', icon: Cpu },
  { year: '02', title: 'QualityGuard™ Launch', description: 'Automated anomaly detection and schema drift isolation turned data confidence into a first-class engineering signal.', icon: ShieldCheck },
  { year: '03', title: 'DataSculpt AI-Ready™ Rollout', description: 'RAG vector embedding preparation and feature store publishing connected governed data to the next generation of AI systems.', icon: Sparkles },
  { year: '04', title: 'Global Enterprise Expansion', description: 'The vision extends to multi-region compute node deployments that bring high-performance data operations closer to every workload.', icon: Globe2 },
];

const regions: Region[] = [
  { name: 'US EAST', location: 'Virginia', position: 'left-[18%] top-[34%]', status: 'ACTIVE REFERENCE NODE' },
  { name: 'EU WEST', location: 'Frankfurt', position: 'left-[48%] top-[29%]', status: 'ACTIVE REFERENCE NODE' },
  { name: 'APAC', location: 'Colombo / Singapore', position: 'left-[78%] top-[58%]', status: 'REGIONAL HUBS' },
];

export default function AboutPage() {
  const [activeMilestone, setActiveMilestone] = useState(0);
  const milestone = milestones[activeMilestone];
  const MilestoneIcon = milestone.icon;

  return <div className="relative mx-auto max-w-7xl px-5 pb-24 pt-10 lg:px-8 lg:pt-14">
    <motion.header initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-4xl text-center"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-500 transition hover:text-brand-300"><span>Home</span><ChevronRight size={14} /><span className="text-brand-300">About DataSculpt</span></Link><div className="mt-8"><span className="inline-flex rounded-full border border-brand-500/30 bg-brand-950/40 px-3.5 py-1.5 font-mono text-xs tracking-[0.16em] text-brand-400">THE DATASCULPT STORY &amp; VISION</span></div><h1 className="mt-6 text-balance text-4xl font-semibold leading-tight tracking-[-0.04em] text-white sm:text-5xl lg:text-6xl">Engineering the Foundation for <span className="bg-gradient-to-r from-brand-200 via-brand-400 to-brand-300 bg-clip-text text-transparent">Enterprise AI.</span></h1><p className="mx-auto mt-6 max-w-3xl text-base leading-7 text-slate-400 sm:text-lg">We are building the high-throughput data engineering layer that transforms fragmented, petabyte-scale datasets into structured, analytics-ready, and AI-ready intelligence.</p></motion.header>

    <section className="mt-24 grid items-center gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:gap-14"><div><p className="eyebrow">THE CORE CHALLENGE</p><h2 className="mt-3 text-3xl font-semibold leading-tight tracking-tight text-white sm:text-4xl">80% of AI Engineering Time is Wasted on Data Preparation.</h2><p className="mt-6 leading-7 text-slate-400">Enterprise data is trapped across legacy databases, messy cloud buckets, and unvalidated pipelines. Traditional CPU ETL tools choke on modern workloads just as teams need more reliable context for analytics and AI.</p><p className="mt-4 leading-7 text-slate-400">DataSculpt exists to turn that preparation bottleneck into an engineering advantage: a unified layer where throughput, quality, and AI readiness are designed together.</p></div><GlassCard className="relative overflow-hidden border-brand-500/40 bg-gradient-to-br from-slate-900 via-brand-950/20 to-slate-900 p-7 sm:p-8"><div className="absolute right-0 top-0 h-32 w-32 rounded-full bg-brand-400/10 blur-3xl" /><div className="relative"><span className="grid h-12 w-12 place-items-center rounded-xl border border-brand-500/30 bg-brand-400/10 text-brand-300"><Target size={22} /></span><p className="mt-7 font-mono text-[0.65rem] uppercase tracking-[0.2em] text-brand-400">THE DATASCULPT INSIGHT</p><h3 className="mt-3 text-2xl font-semibold leading-tight text-white">Hardware, memory, and quality must work as one system.</h3><p className="mt-4 leading-7 text-slate-300">DataSculpt was created to combine hardware acceleration through NVIDIA CUDA/cuDF, zero-copy Apache Arrow memory, and continuous AI quality validation into a unified control plane.</p></div></GlassCard></section>

    <section className="mt-24 lg:mt-32"><p className="eyebrow">HOW WE BUILD</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Four principles behind every layer.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{principles.map((principle, index) => <PrincipleCard key={principle.title} principle={principle} index={index} />)}</div></section>

    <section className="mt-24 lg:mt-32"><div className="grid items-start gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-16"><div><p className="eyebrow">VISION ROADMAP / EVOLUTION</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">A long view of the data layer.</h2><p className="mt-5 leading-7 text-slate-400">Our milestones represent the engineering sequence we believe enterprise AI infrastructure needs: accelerate the work, verify the signal, prepare the context, then bring it closer to every region.</p><div className="mt-8 flex items-center gap-3 rounded-xl border border-brand-500/20 bg-brand-950/20 p-4"><Workflow size={18} className="text-brand-300" /><span className="font-mono text-[0.65rem] uppercase tracking-wider text-brand-300">Vision reference model — not live telemetry</span></div></div><div className="grid gap-6 md:grid-cols-[0.72fr_1.28fr]"><div className="relative space-y-2"><div className="absolute bottom-5 left-[21px] top-5 w-px bg-brand-500/30" />{milestones.map((item, index) => <button key={item.year} type="button" onClick={() => setActiveMilestone(index)} aria-pressed={activeMilestone === index} className={`relative z-10 flex w-full items-center gap-3 rounded-xl border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-300 ${activeMilestone === index ? 'border-brand-400/60 bg-brand-400 text-slate-950' : 'border-transparent bg-slate-900/50 text-slate-400 hover:border-brand-500/30 hover:text-brand-300'}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full font-mono text-xs ${activeMilestone === index ? 'bg-slate-950/10 text-slate-950' : 'bg-slate-950 text-brand-300'}`}>{item.year}</span><span className="truncate text-sm font-semibold">{item.title}</span></button>)}</div><AnimatePresence mode="wait"><motion.div key={milestone.year} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }} className="min-h-[260px]"><GlassCard className="h-full border-brand-500/30 p-6 sm:p-7"><MilestoneIcon size={24} className="text-brand-300" /><p className="mt-6 font-mono text-xs uppercase tracking-[0.18em] text-brand-400">MILESTONE {milestone.year}</p><h3 className="mt-3 text-2xl font-semibold text-white">{milestone.title}</h3><p className="mt-4 leading-7 text-slate-400">{milestone.description}</p></GlassCard></motion.div></AnimatePresence></div></div></section>

    <section className="mt-24 lg:mt-32"><div className="grid items-center gap-8 lg:grid-cols-[1.15fr_0.85fr]"><GlassCard className="relative min-h-[330px] overflow-hidden p-6 sm:p-8"><div className="absolute inset-0 opacity-60"><div className="absolute left-[20%] top-[36%] h-px w-[30%] rotate-[-8deg] bg-brand-500/30" /><div className="absolute left-[49%] top-[31%] h-px w-[31%] rotate-[17deg] bg-brand-500/30" /><div className="absolute left-[23%] top-[37%] h-[25%] w-px rotate-[15deg] bg-brand-500/20" /></div><div className="relative"><div className="flex items-start justify-between"><div><p className="eyebrow">REGIONAL INFRASTRUCTURE FOOTPRINT</p><h2 className="mt-3 text-2xl font-semibold text-white sm:text-3xl">Innovation closer to the workload.</h2></div><Globe2 size={25} className="text-brand-300" /></div><div className="relative mt-8 h-48 rounded-xl border border-slate-800 bg-slate-950/60">{regions.map((region) => <div key={region.name} className={`absolute ${region.position}`}><span className="relative block h-4 w-4 rounded-full bg-brand-300 shadow-[0_0_18px_rgba(234,179,8,0.55)]"><span className="absolute inset-[-7px] animate-ping rounded-full border border-brand-400/30" /></span><div className="mt-2 whitespace-nowrap font-mono text-[0.58rem] text-brand-300"><strong className="block text-[0.62rem]">{region.name}</strong><span className="text-slate-500">{region.location}</span></div></div>)}</div></div></GlassCard><div><p className="eyebrow">REFERENCE FOOTPRINT</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">Regional by design. Sovereign by default.</h2><p className="mt-5 leading-7 text-slate-400">DataSculpt&apos;s infrastructure vision places compute and engineering context closer to the teams and datasets it serves.</p><div className="mt-6 space-y-3">{regions.map((region) => <div key={region.name} className="flex items-center gap-3 rounded-lg border border-slate-800 bg-slate-900/60 p-3"><span className="h-2 w-2 rounded-full bg-brand-300" /><div><p className="text-sm font-semibold text-slate-200">{region.name} <span className="font-normal text-slate-500">/ {region.location}</span></p><p className="mt-1 font-mono text-[0.58rem] uppercase tracking-wider text-brand-400">{region.status}</p></div></div>)}</div></div></div></section>

    <motion.section id="careers" initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} className="mt-24 scroll-mt-24 rounded-2xl border border-brand-500/30 bg-gradient-to-r from-slate-900 via-brand-950/20 to-slate-900 p-8 text-center shadow-[0_0_30px_rgba(234,179,8,0.08)] sm:p-10 lg:mt-32"><p className="eyebrow">JOIN THE BUILD</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-semibold tracking-tight text-white sm:text-4xl">Want to Help Shape the Future of AI Data Systems?</h2><p id="contact-architects" className="mx-auto mt-4 max-w-2xl scroll-mt-24 text-sm leading-6 text-slate-400">Careers and architect conversations are currently coordinated directly with the DataSculpt team.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button href="#careers">Explore Open Engineering Roles <ArrowRight size={16} /></Button><Button href="#contact-architects" variant="ghost">Contact Our Architects <MessageIcon /></Button></div></motion.section>
  </div>;
}

function PrincipleCard({ principle, index }: { principle: Principle; index: number }) {
  const Icon = principle.icon;
  return <motion.div initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: index * 0.06 }}><GlassCard className="h-full p-6 transition duration-200 hover:border-brand-500/50"><span className="grid h-11 w-11 place-items-center rounded-xl border border-brand-500/30 bg-brand-400/10 text-brand-300"><Icon size={20} /></span><p className="mt-6 font-mono text-[0.62rem] uppercase tracking-[0.16em] text-brand-400">{principle.label}</p><h3 className="mt-2 text-lg font-semibold text-white">{principle.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{principle.description}</p><div className="mt-6 flex items-center gap-2 border-t border-slate-800 pt-4 font-mono text-[0.62rem] uppercase tracking-wider text-slate-500"><Check size={14} className="text-brand-300" />Engineering principle</div></GlassCard></motion.div>;
}

function MessageIcon() { return <ArrowRight size={15} />; }
