'use client';

import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowRight } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/Button';
import { aiOutcomes } from './homeData';
import { Reveal } from './Reveal';

export function AIOutcomes() {
  const reducedMotion = useReducedMotion();
  const [hovered, setHovered] = useState<number | null>(null);
  const phrases = ['Find what matters.', 'See what’s next.', 'Understand every signal.', 'Act with confidence.'];
  return <section aria-labelledby="ai-outcomes-title" className="-mt-20 overflow-hidden bg-yellow-50 lg:-mt-28"><div className="grid items-stretch lg:grid-cols-2"><div className="order-2 px-5 sm:px-10 lg:order-1 lg:px-[max(2rem,calc((100vw-80rem)/2))] lg:py-28"><Reveal><p className="eyebrow">AI-READY BY DESIGN</p><h2 id="ai-outcomes-title" className="mt-4 max-w-xl text-4xl font-semibold leading-tight tracking-tight text-slate-800 sm:text-5xl">Make AI useful from the foundation up.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">DataSculpt helps teams prepare trusted information for the moments when better answers, clearer forecasts, and confident action matter most.</p><Button href="/products/" variant="ghost" className="mt-7">See how the platform helps <ArrowRight size={15} /></Button></Reveal><div className="mt-14 space-y-3 sm:mt-20">{aiOutcomes.map(([title, description, Icon], index) => <motion.article key={title} onMouseEnter={() => setHovered(index)} onMouseLeave={() => setHovered(null)} className={`border-l-2 px-5 py-7 transition sm:px-7 ${hovered === index ? 'border-brand-500 bg-white/75 shadow-panel' : 'border-brand-100/80 hover:border-brand-300 hover:bg-white/45'}`} whileHover={reducedMotion ? undefined : { x: 4 }}><span className="flex items-start gap-4"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl border ${hovered === index ? 'border-brand-400 bg-brand-400 text-slate-950' : 'border-brand-200 bg-brand-50 text-brand-600'}`}><Icon size={20} /></span><span><span className="block text-xl font-semibold text-slate-800">{title}</span><span className="mt-2 block max-w-lg text-sm leading-6 text-slate-500">{description}</span></span></span></motion.article>)}</div></div><div className="order-1 min-h-[720px] lg:order-2 lg:min-h-[1080px]"><div className="relative h-full min-h-[720px]"><div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1600&q=85')] bg-cover bg-center" aria-hidden="true" /><div className="absolute inset-0 bg-gradient-to-r from-yellow-50 via-yellow-50/15 to-transparent lg:from-yellow-50/90 lg:via-yellow-50/10" aria-hidden="true" /><AnimatePresence mode="wait"><motion.div key={hovered ?? 'default'} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: reducedMotion ? 0 : 0.2 }} className="absolute bottom-8 left-5 z-10 max-w-[19rem] border-l-2 border-brand-400 bg-white/85 px-5 py-4 shadow-panel backdrop-blur-md lg:left-0"><p className="font-mono text-[0.62rem] font-semibold tracking-[0.18em] text-brand-600">AI-READY FOUNDATION</p><p className="mt-2 text-xl font-semibold text-slate-800">{hovered === null ? 'Trusted data for what comes next.' : phrases[hovered]}</p></motion.div></AnimatePresence></div></div></div></section>;
}
