'use client';

import { LogOut, Mail, ShieldCheck, UserRound } from 'lucide-react';
import { useAuth } from '@/components/auth/AuthContext';
import { useWorkspace } from '@/components/dashboard/WorkspaceContext';
import { WorkspaceButton, WorkspacePageHeader, WorkspacePanel } from '@/components/dashboard/WorkspaceUI';

export default function AccountPage() {
  const { user, logout } = useAuth();
  const { plan, loading: planLoading } = useWorkspace();
  if (!user) return null;
  const name = [user.first_name, user.last_name].filter(Boolean).join(' ') || user.username || 'DataSculpt user';
  return <div className="mx-auto max-w-[1200px] px-4 py-8 sm:px-6 lg:px-8 lg:py-10"><WorkspacePageHeader eyebrow="Account" title="Your workspace identity." description="Review the identity connected to this browser session and the plan currently associated with your DataSculpt account." /><section className="mt-8 grid gap-5 lg:grid-cols-2"><WorkspacePanel className="p-6 sm:p-7"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-100 text-brand-800"><UserRound size={22} /></span><div><p className="text-xl font-semibold text-[#29251d]">{name}</p><p className="mt-1 text-sm text-[#756f61]">{user.username ? `@${user.username}` : 'Username not provided'}</p></div></div><dl className="mt-7 divide-y divide-[#ebe6da]"><div className="grid gap-2 py-4 sm:grid-cols-[0.45fr_1fr]"><dt className="text-xs font-semibold uppercase tracking-[0.13em] text-[#817a6b]">Email</dt><dd className="flex items-center gap-2 text-sm text-[#403b31]"><Mail size={14} className="text-brand-700" />{user.email || 'Not available'}</dd></div><div className="grid gap-2 py-4 sm:grid-cols-[0.45fr_1fr]"><dt className="text-xs font-semibold uppercase tracking-[0.13em] text-[#817a6b]">Sign-in method</dt><dd className="text-sm capitalize text-[#403b31]">{user.provider_name || 'Password account'}</dd></div><div className="grid gap-2 py-4 sm:grid-cols-[0.45fr_1fr]"><dt className="text-xs font-semibold uppercase tracking-[0.13em] text-[#817a6b]">Email status</dt><dd className="flex items-center gap-2 text-sm text-[#403b31]"><ShieldCheck size={14} className="text-brand-700" />{user.email_verified_at ? 'Verified' : 'Verification not confirmed'}</dd></div></dl></WorkspacePanel><WorkspacePanel className="p-6 sm:p-7"><p className="text-[0.64rem] font-semibold uppercase tracking-[0.16em] text-brand-700">Workspace access</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-[#29251d]">{planLoading ? 'Checking plan…' : `${plan?.name || 'Starter'} plan`}</h2><p className="mt-3 text-sm leading-6 text-[#6e6859]">{plan?.description || 'Plan details are currently unavailable.'}</p><div className="mt-6 rounded-xl border border-[#ded8c8] bg-[#faf8f1] p-4"><p className="text-xs font-semibold text-[#4a453a]">Session storage</p><p className="mt-2 text-xs leading-5 text-[#756f61]">This static frontend keeps the Sanctum bearer token and safe user fields in this browser. Passwords and payment-card details are never stored here.</p></div><WorkspaceButton onClick={() => void logout().then(() => window.location.replace('/auth/login/'))} className="mt-6 border-[#29251d] bg-[#29251d] text-[#fff7d7] hover:bg-[#3b372d]"><LogOut size={16} />Sign out</WorkspaceButton></WorkspacePanel></section></div>;
}
