'use client';

import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, CheckCircle2, ChevronRight, CircleHelp, FileText, Printer, Scale, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/Button';
import { GlassCard } from '@/components/ui/GlassCard';

type LegalSection = { id: string; title: string; summary: string; paragraphs: string[]; icon: typeof Scale };

const sections: LegalSection[] = [
  { id: 'platform-usage', title: 'Platform Usage & License Scope', summary: 'Your right to use DataSculpt depends on the plan, account permissions, and product scope agreed for your organization.', icon: FileText, paragraphs: ['DataSculpt grants an authorized customer a limited, non-exclusive, non-transferable right to access and use the platform during the applicable subscription term. Access is intended for the customer’s internal data engineering, analytics, and AI preparation workflows.', 'Customers are responsible for maintaining accurate account information, protecting credentials, and ensuring that users operate within the permissions and compute allocation associated with the selected plan. Resale, unauthorized copying, reverse engineering, or interference with the platform is not permitted.'] },
  { id: 'compute-sla', title: 'GPU Compute Allocation & SLA', summary: 'Compute capacity and availability commitments are tied to the selected tier and any negotiated order or SLA.', icon: Scale, paragraphs: ['Usage metrics are measured against allocated GPU processing hours and cuDF/CUDA node capacity. Actual allocation, concurrency, overage handling, and support response commitments are defined by the applicable plan or enterprise order form.', 'Subject to the applicable SLA and exclusions, Scale tiers target 99.9% uptime and Enterprise VPC clusters target 99.99% uptime. Scheduled maintenance, customer-controlled infrastructure, force majeure events, and third-party failures may be excluded from availability calculations.'] },
  { id: 'data-ownership', title: 'Data Processing & Customer Ownership', summary: 'Customers retain ownership of their submitted data and control the purposes for which it is processed.', icon: ShieldCheck, paragraphs: ['You retain 100% ownership of raw data, schemas, derived datasets, and AI feature embeddings that you submit to or generate through DataSculpt. DataSculpt does not sell customer datasets or use customer data to train public models without a separate written agreement.', 'You authorize DataSculpt to process customer content only as needed to provide, secure, maintain, and improve the contracted services. You are responsible for having the rights, notices, and permissions necessary for the data and instructions you provide.'] },
  { id: 'acceptable-use', title: 'Acceptable Use & Security Protocols', summary: 'Platform access must support lawful, secure workloads and must not create risk for other customers or infrastructure.', icon: ShieldCheck, paragraphs: ['Customers may not use the platform to violate applicable law, infringe rights, distribute malicious code, bypass access controls, or probe systems without authorization. High-risk or regulated workloads require an agreed deployment and security review.', 'Each party will maintain reasonable administrative, technical, and organizational safeguards. Customers must secure credentials, configure access boundaries, review outputs, and promptly report suspected compromise or unauthorized use.'] },
  { id: 'billing', title: 'Subscription & Compute Billing', summary: 'Subscription fees, compute allocation, billing cycle, and applicable usage charges are determined by the selected plan and order terms.', icon: FileText, paragraphs: ['Fees are billed according to the pricing, interval, currency, and compute terms presented at purchase or in an enterprise order form. Usage-based compute may be measured in GPU processing hours, node allocation, or another agreed metric.', 'Unless an order form states otherwise, invoices are due under the payment terms presented at checkout or contracting. Customers are responsible for applicable taxes and for reviewing usage before renewal or expansion.'] },
  { id: 'liability', title: 'Limitation of Liability & Warranties', summary: 'The service is provided with commitments defined by the applicable plan, SLA, and order documentation.', icon: AlertTriangle, paragraphs: ['DataSculpt will provide the platform with reasonable care and skill and will work to meet the service commitments expressly stated in the applicable SLA. Except for express written commitments, the platform is provided on an as-available basis and customers remain responsible for validating outputs and maintaining appropriate backups.', 'To the extent permitted by law, neither party is liable for indirect, incidental, special, consequential, or punitive damages, or for lost profits, revenue, or data. Any aggregate liability cap and negotiated exceptions will be defined in the applicable order form or SLA.'] },
  { id: 'termination', title: 'Termination & Account Cancellation', summary: 'Access can end when a subscription expires, a customer cancels under its plan, or a material breach remains uncured.', icon: CircleHelp, paragraphs: ['A customer may cancel or decline renewal according to the notice period and process stated in the applicable plan or order form. Either party may suspend or terminate access for material breach, non-payment, security risk, or unlawful use, subject to any required notice and cure period.', 'After termination, access ends and outstanding payment obligations remain due. Data export, retention, and deletion are handled according to the customer’s plan, order form, and documented retention commitments.'] },
  { id: 'governing-law', title: 'Governing Law & Dispute Resolution', summary: 'The applicable contracting documents determine governing law, venue, escalation, and dispute resolution procedures.', icon: Scale, paragraphs: ['The governing law, venue, arbitration terms, and escalation process for a customer relationship will be stated in the applicable order form or enterprise agreement. Before formal proceedings, the parties should first make a good-faith effort to resolve a dispute through their designated business and legal contacts.', 'If these online terms conflict with a signed enterprise agreement, the signed agreement controls for the conflicting subject matter.'] },
];

export default function TermsPage() {
  const [activeId, setActiveId] = useState(sections[0].id);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)[0];
      if (visible) setActiveId(visible.target.id);
    }, { rootMargin: '-18% 0px -68% 0px', threshold: [0, 0.1, 0.5] });
    sections.forEach((section) => { const element = document.getElementById(section.id); if (element) observer.observe(element); });
    return () => observer.disconnect();
  }, []);

  return <div className="relative mx-auto max-w-7xl px-5 pb-24 pt-10 lg:px-8 lg:pt-14">
    <motion.header initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-4xl text-center print:max-w-none"><Link href="/" className="no-print inline-flex items-center gap-2 text-sm text-slate-500 transition hover:text-brand-300"><span>Home</span><ChevronRight size={14} /><span className="text-brand-300">Terms of Service</span></Link><div className="mt-8"><span className="inline-flex rounded-full border border-brand-500/30 bg-brand-950/40 px-3.5 py-1.5 font-mono text-xs tracking-[0.16em] text-brand-400">LEGAL &amp; ENTERPRISE GOVERNANCE</span></div><h1 className="mt-6 text-4xl font-semibold tracking-[-0.04em] text-white sm:text-5xl">Terms of Service</h1><p className="mt-4 font-mono text-sm text-slate-500">Effective Date: August 2026 <span className="mx-2 text-brand-500">|</span> Version 2.4</p><button type="button" onClick={() => window.print()} className="no-print mt-7 inline-flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-900/70 px-4 py-2.5 text-sm font-semibold text-slate-300 transition hover:border-brand-500/50 hover:text-brand-300"><Printer size={16} />Print Document</button></motion.header>

    <div className="mt-16 grid items-start gap-10 lg:grid-cols-[0.27fr_0.73fr] lg:gap-14"><aside className="no-print lg:sticky lg:top-8"><div className="mb-4 flex items-center gap-2"><FileText size={16} className="text-brand-300" /><p className="eyebrow">ON THIS PAGE</p></div><nav aria-label="Terms sections" className="space-y-1">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={`block border-l-2 px-3 py-2 text-sm transition ${activeId === section.id ? 'border-brand-400 bg-brand-950/20 font-medium text-brand-300' : 'border-slate-800 text-slate-500 hover:border-brand-500/40 hover:text-brand-300'}`}>{section.title}</a>)}</nav></aside><main className="min-w-0"><div className="mb-8 flex gap-3 rounded-xl border-l-4 border-brand-400 bg-brand-950/20 p-5 text-sm leading-6 text-slate-300"><AlertTriangle size={18} className="mt-0.5 shrink-0 text-brand-300" /><p><strong className="text-brand-300">Draft legal document:</strong> These terms describe the current product and enterprise service model. Have qualified counsel review them before execution or relying on them for a specific transaction.</p></div><div className="space-y-10">{sections.map((section) => <LegalSectionView key={section.id} section={section} />)}</div><GlassCard className="mt-12 flex flex-col items-center justify-between gap-6 border-brand-500/30 p-8 text-center md:flex-row md:text-left"><div><p className="eyebrow">LEGAL SUPPORT</p><h2 className="mt-2 text-xl font-semibold text-white">Have questions regarding our enterprise terms or custom SLA agreements?</h2></div><Button href="/contact/">Contact Legal &amp; Compliance Team <ChevronRight size={16} /></Button></GlassCard></main></div>
  </div>;
}

function LegalSectionView({ section }: { section: LegalSection }) {
  const Icon = section.icon;
  return <motion.section id={section.id} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} className="scroll-mt-8"><div className="flex items-start gap-4"><span className="no-print grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-brand-500/30 bg-brand-400/10 text-brand-300"><Icon size={18} /></span><div className="min-w-0"><h2 className="text-2xl font-semibold tracking-tight text-white sm:text-3xl">{section.title}</h2><p className="mt-3 max-w-3xl text-base leading-7 text-slate-400">{section.summary}</p></div></div><div className="mt-5 space-y-4 border-l border-slate-800 pl-5 text-sm leading-7 text-slate-300 sm:pl-14">{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.id === 'data-ownership' && <Callout>Summary: You retain 100% ownership of all raw data, schemas, and AI feature embeddings processed through DataSculpt. We never sell or train public models on your customer datasets.</Callout>}{section.id === 'compute-sla' && <Callout>Service commitment: Scale tiers target 99.9% uptime and Enterprise VPC clusters target 99.99% uptime, subject to the applicable SLA, exclusions, and order terms.</Callout>}{section.id === 'acceptable-use' && <Callout>Security responsibility: Customers control their data, credentials, access boundaries, and lawful use of the platform. DataSculpt maintains safeguards for the service environment.</Callout>}{section.id === 'billing' && <Callout>Billing reminder: Compute allocation is measured against GPU processing hours and cuDF/CUDA node capacity under the applicable plan or enterprise agreement.</Callout>}</div></motion.section>;
}

function Callout({ children }: { children: React.ReactNode }) { return <div className="my-6 rounded-r-xl border-l-4 border-brand-400 bg-slate-900/90 p-5 text-sm leading-6 text-slate-300"><span className="font-semibold text-brand-300">Plain-English summary: </span>{children}</div>; }
